# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cd1Q9fn6k29oOieT7PmwlpjPwIHnBJB_
"""

# ============================================================
# CELL 1 — CUSTOMER SUPPORT AI
# Install and Import Required Libraries
# ============================================================


import pandas as pd
import numpy as np
import re
import json
import uuid
from datetime import datetime

print("✅ Libraries imported successfully!")
print("✅ Customer Support AI environment is ready.")

# ============================================================
# CELL 2 — CUSTOMER DATABASE
# ============================================================

customers = {
    "CUST1001": {
        "name": "Rahul Sharma",
        "email": "rahul@example.com",
        "plan": "Premium",
        "location": "Delhi",
        "previous_issues": [
            "Payment failed once",
            "Order delivery delayed"
        ],
        "total_orders": 8,
        "previous_tickets": 2
    },

    "CUST1002": {
        "name": "Priya Singh",
        "email": "priya@example.com",
        "plan": "Basic",
        "location": "Lucknow",
        "previous_issues": [
            "Password reset"
        ],
        "total_orders": 3,
        "previous_tickets": 1
    },

    "CUST1003": {
        "name": "Aman Verma",
        "email": "aman@example.com",
        "plan": "Premium",
        "location": "Kanpur",
        "previous_issues": [
            "Product damaged",
            "Refund requested"
        ],
        "total_orders": 12,
        "previous_tickets": 3
    }
}

print("✅ Customer database loaded.")
print("👥 Total customers:", len(customers))
print("\nAvailable Customer IDs:")

for customer_id in customers:
    print("•", customer_id)

# ============================================================
# CELL 3 — COMPANY KNOWLEDGE BASE
# ============================================================

knowledge_base = {

    "payment_failed": {
        "category": "Billing",
        "policy": "If money is deducted but the order is not confirmed, verify the payment status and create a refund request.",
        "action": "Create refund request",
        "escalation": True
    },

    "refund": {
        "category": "Billing",
        "policy": "Eligible refunds are processed after payment/order verification.",
        "action": "Create refund request",
        "escalation": False
    },

    "order_delay": {
        "category": "Order",
        "policy": "Check the latest delivery status. If the order is significantly delayed, create a priority delivery ticket.",
        "action": "Create delivery support ticket",
        "escalation": False
    },

    "damaged_product": {
        "category": "Order",
        "policy": "Damaged products can be reported for replacement or refund after verification.",
        "action": "Create replacement/refund ticket",
        "escalation": True
    },

    "password": {
        "category": "Account",
        "policy": "Customers can reset their password using the registered email.",
        "action": "Send password reset instructions",
        "escalation": False
    },

    "technical": {
        "category": "Technical",
        "policy": "Collect error details and troubleshooting information. Escalate unresolved technical issues.",
        "action": "Create technical support ticket",
        "escalation": True
    }
}

print("✅ Knowledge base loaded.")
print("📚 Total knowledge articles:", len(knowledge_base))

print("\nAvailable topics:")
for topic in knowledge_base:
    print("•", topic)

def analyze_message(message):

    text = message.lower()

    # -----------------------------
    # INTENT DETECTION
    # -----------------------------

    if any(word in text for word in [
        "payment", "paid", "payment failed",
        "money deducted", "money cut", "charged"
    ]):
        intent = "Billing"
        topic = "payment_failed"

    elif any(word in text for word in [
        "refund", "return my money", "money back"
    ]):
        intent = "Billing"
        topic = "refund"

    elif any(word in text for word in [
        "delivery", "delivered", "late",
        "delay", "order not received"
    ]):
        intent = "Order"
        topic = "order_delay"

    elif any(word in text for word in [
        "damaged", "broken", "defective"
    ]):
        intent = "Order"
        topic = "damaged_product"

    elif any(word in text for word in [
        "password", "login", "sign in", "account"
    ]):
        intent = "Account"
        topic = "password"

    elif any(word in text for word in [
        "error", "bug", "crash", "not working",
        "technical", "website down", "app not working"
    ]):
        intent = "Technical"
        topic = "technical"

    else:
        intent = "General"
        topic = "technical"

    # -----------------------------
    # SENTIMENT DETECTION
    # -----------------------------

    negative_words = [
        "angry", "frustrated", "worst", "terrible",
        "useless", "hate", "complaint", "disappointed",
        "ridiculous", "bad", "urgent"
    ]

    positive_words = [
        "thanks", "thank you", "good",
        "great", "happy", "excellent"
    ]

    negative_score = sum(word in text for word in negative_words)
    positive_score = sum(word in text for word in positive_words)

    if negative_score > positive_score:
        sentiment = "Negative"
    elif positive_score > negative_score:
        sentiment = "Positive"
    else:
        sentiment = "Neutral"

    # -----------------------------
    # URGENCY DETECTION
    # -----------------------------

    high_urgency_words = [
        "urgent", "immediately", "asap",
        "emergency", "right now", "fraud",
        "money deducted", "account hacked"
    ]

    if any(word in text for word in high_urgency_words):
        urgency = "High"
    elif any(word in text for word in [
        "soon", "delay", "waiting"
    ]):
        urgency = "Medium"
    else:
        urgency = "Low"

    return {
        "intent": intent,
        "topic": topic,
        "sentiment": sentiment,
        "urgency": urgency
    }


print("✅ AI analysis engine created.")

# Test
test_message = "My money was deducted but my order was not confirmed. Please help urgently."

result = analyze_message(test_message)

print("\nTest Message:")
print(test_message)

print("\nAI Analysis:")
print(json.dumps(result, indent=2))

# ============================================================
# CELL 5 — CUSTOMER CONTEXT ENGINE
# ============================================================

def get_customer_context(customer_id):

    if customer_id not in customers:
        return {
            "found": False,
            "message": "Customer not found."
        }

    customer = customers[customer_id]

    return {
        "found": True,
        "customer_id": customer_id,
        "name": customer["name"],
        "email": customer["email"],
        "plan": customer["plan"],
        "location": customer["location"],
        "previous_issues": customer["previous_issues"],
        "total_orders": customer["total_orders"],
        "previous_tickets": customer["previous_tickets"]
    }


print("✅ Customer context engine created.")

context = get_customer_context("CUST1001")

print("\nCustomer Context:")
print(json.dumps(context, indent=2))

# ============================================================
# CELL 6 — AUTONOMOUS ACTION ENGINE
# ============================================================

def perform_action(topic, urgency, sentiment, customer_context):

    article = knowledge_base.get(topic)

    if article is None:
        return {
            "action": "Create general support ticket",
            "escalation": True,
            "reason": "No matching knowledge article found."
        }

    action = article["action"]
    escalation = article["escalation"]
    reason = "Policy-based action selected."

    # Escalate high-risk cases
    if urgency == "High":
        escalation = True
        reason = "High urgency detected."

    if sentiment == "Negative" and urgency == "High":
        escalation = True
        reason = "High urgency + negative customer sentiment."

    # Previous repeated issues
    if customer_context.get("previous_tickets", 0) >= 3:
        escalation = True
        reason = "Customer has multiple previous support tickets."

    return {
        "action": action,
        "escalation": escalation,
        "reason": reason
    }


print("✅ Autonomous action engine created.")

# ============================================================
# CELL 7 — COMPLETE AUTONOMOUS CUSTOMER SUPPORT AGENT
# ============================================================

support_sessions = {}


def customer_support_agent(customer_id, message):

    # ---------------------------------------
    # STEP 1 — Customer Context
    # ---------------------------------------

    customer_context = get_customer_context(customer_id)

    if not customer_context["found"]:
        return {
            "status": "ERROR",
            "message": "Customer ID not found."
        }

    # ---------------------------------------
    # STEP 2 — Analyze Message
    # ---------------------------------------

    analysis = analyze_message(message)

    # ---------------------------------------
    # STEP 3 — Knowledge Reasoning
    # ---------------------------------------

    topic = analysis["topic"]
    article = knowledge_base.get(topic)

    # ---------------------------------------
    # STEP 4 — Autonomous Action
    # ---------------------------------------

    action_result = perform_action(
        topic,
        analysis["urgency"],
        analysis["sentiment"],
        customer_context
    )

    # ---------------------------------------
    # STEP 5 — Ticket ID
    # ---------------------------------------

    ticket_id = "TKT-" + str(uuid.uuid4())[:8].upper()

    # ---------------------------------------
    # STEP 6 — Response Generation
    # ---------------------------------------

    if action_result["escalation"]:
        status = "ESCALATED"

        response = (
            f"Hello {customer_context['name']}, "
            f"I understand your {analysis['intent'].lower()} issue. "
            f"I have investigated your request and initiated: "
            f"{action_result['action']}. "
            f"Because this case requires additional attention, "
            f"I have escalated it to a human support agent. "
            f"Your ticket ID is {ticket_id}."
        )
    else:
        status = "RESOLVED"

        response = (
            f"Hello {customer_context['name']}, "
            f"I have identified your issue as a {analysis['intent'].lower()} request. "
            f"Based on our support policy, I have initiated: "
            f"{action_result['action']}. "
            f"Your ticket ID is {ticket_id}."
        )

    # ---------------------------------------
    # STEP 7 — Complete Human Handoff Context
    # ---------------------------------------

    handoff_context = {
        "ticket_id": ticket_id,
        "customer_id": customer_id,
        "customer_name": customer_context["name"],
        "customer_plan": customer_context["plan"],
        "customer_history": customer_context["previous_issues"],
        "customer_message": message,
        "detected_intent": analysis["intent"],
        "sentiment": analysis["sentiment"],
        "urgency": analysis["urgency"],
        "knowledge_topic": topic,
        "policy": article["policy"] if article else "No policy found",
        "action_taken": action_result["action"],
        "escalation_reason": action_result["reason"],
        "status": status
    }

    # ---------------------------------------
    # STEP 8 — Context Retention
    # ---------------------------------------

    if customer_id not in support_sessions:
        support_sessions[customer_id] = []

    support_sessions[customer_id].append({
        "customer_message": message,
        "ticket_id": ticket_id,
        "status": status
    })

    return {
        "status": status,
        "ticket_id": ticket_id,
        "response": response,
        "analysis": analysis,
        "customer_context": customer_context,
        "knowledge": article,
        "action": action_result,
        "handoff_context": handoff_context
    }


print("✅ COMPLETE AUTONOMOUS CUSTOMER SUPPORT AGENT READY!")

# ============================================================
# CELL 8 — TEST CASE 1
# ============================================================

customer_id = "CUST1001"

message = (
    "My money was deducted but my order was not confirmed. "
    "This is urgent and I am very frustrated."
)

result = customer_support_agent(customer_id, message)

print("=" * 70)
print("🤖 AUTONOMOUS CUSTOMER SUPPORT AI")
print("=" * 70)

print("\n👤 CUSTOMER")
print("ID:", customer_id)
print("Message:", message)

print("\n🧠 AI ANALYSIS")
print("Intent:", result["analysis"]["intent"])
print("Urgency:", result["analysis"]["urgency"])
print("Sentiment:", result["analysis"]["sentiment"])

print("\n📚 KNOWLEDGE REASONING")
print("Category:", result["knowledge"]["category"])
print("Policy:", result["knowledge"]["policy"])

print("\n⚙️ AUTONOMOUS ACTION")
print("Action:", result["action"]["action"])

print("\n🚨 ESCALATION")
print("Status:", result["status"])
print("Reason:", result["action"]["reason"])

print("\n💬 AI RESPONSE")
print(result["response"])

print("\n🎫 TICKET")
print(result["ticket_id"])

print("\n🤝 HUMAN HANDOFF CONTEXT")
print(json.dumps(result["handoff_context"], indent=2))

print("=" * 70)

# ============================================================
# CELL 9 — CONTEXT RETENTION DEMO
# ============================================================

print("=" * 70)
print("🧠 CUSTOMER MEMORY / CONTEXT RETENTION")
print("=" * 70)

customer_id = "CUST1001"

print("\nCustomer:", customers[customer_id]["name"])

print("\nPrevious Support Sessions:")

if customer_id in support_sessions:
    for i, session in enumerate(support_sessions[customer_id], 1):
        print(f"\nSession {i}")
        print("Ticket:", session["ticket_id"])
        print("Message:", session["customer_message"])
        print("Status:", session["status"])
else:
    print("No previous sessions found.")

print("\n✅ Context retained successfully.")

# ============================================================
# CELL 10 — MULTIPLE CUSTOMER SCENARIOS
# ============================================================

test_cases = [
    (
        "CUST1002",
        "I forgot my password and cannot login."
    ),

    (
        "CUST1003",
        "My product arrived damaged. I want a replacement."
    ),

    (
        "CUST1001",
        "My order delivery is delayed. Please check it."
    ),

    (
        "CUST1002",
        "The mobile app keeps crashing and shows an error."
    )
]


for customer_id, message in test_cases:

    result = customer_support_agent(customer_id, message)

    print("\n" + "=" * 70)
    print("CUSTOMER:", customer_id)
    print("MESSAGE:", message)

    print("\nIntent:", result["analysis"]["intent"])
    print("Urgency:", result["analysis"]["urgency"])
    print("Sentiment:", result["analysis"]["sentiment"])
    print("Action:", result["action"]["action"])
    print("Status:", result["status"])
    print("Ticket:", result["ticket_id"])

# ============================================================
# CELL 11 — GRADIO CUSTOMER SUPPORT DASHBOARD
# ============================================================

import gradio as gr


def run_support(customer_id, message):

    if not customer_id or not message:
        return (
            "⚠️ Please enter Customer ID and Customer Message.",
            "",
            "",
            "",
            "",
            ""
        )

    result = customer_support_agent(
        customer_id.strip(),
        message.strip()
    )

    if result.get("status") == "ERROR":
        return (
            result["message"],
            "",
            "",
            "",
            "",
            ""
        )

    analysis = result["analysis"]
    action = result["action"]
    customer = result["customer_context"]

    customer_info = (
        f"Name: {customer['name']}\n"
        f"Plan: {customer['plan']}\n"
        f"Location: {customer['location']}\n"
        f"Previous Tickets: {customer['previous_tickets']}\n"
        f"Previous Issues: {', '.join(customer['previous_issues'])}"
    )

    analysis_info = (
        f"Intent: {analysis['intent']}\n"
        f"Urgency: {analysis['urgency']}\n"
        f"Sentiment: {analysis['sentiment']}\n"
        f"Topic: {analysis['topic']}"
    )

    action_info = (
        f"Action Taken: {action['action']}\n"
        f"Escalation: {'YES 🚨' if action['escalation'] else 'NO ✅'}\n"
        f"Reason: {action['reason']}"
    )

    knowledge_info = (
        f"Category: {result['knowledge']['category']}\n\n"
        f"Policy:\n{result['knowledge']['policy']}"
    )

    handoff_info = json.dumps(
        result["handoff_context"],
        indent=2
    )

    return (
        result["response"],
        customer_info,
        analysis_info,
        action_info,
        knowledge_info,
        handoff_info
    )


with gr.Blocks(title="AI Customer Support Command Center") as demo:

    gr.Markdown(
        """
        # 🤖 AI CUSTOMER SUPPORT COMMAND CENTER

        ### Autonomous • Context-Aware • Action-Oriented • Human Handoff

        **Track 2 — Customer Support**
        """
    )

    with gr.Row():

        with gr.Column():

            customer_id = gr.Textbox(
                label="Customer ID",
                value="CUST1001",
                placeholder="Example: CUST1001"
            )

            message = gr.Textbox(
                label="Customer Message",
                placeholder="Type customer complaint here...",
                lines=5
            )

            analyze_button = gr.Button(
                "🚀 Analyze & Resolve",
                variant="primary"
            )

        with gr.Column():

            response = gr.Textbox(
                label="🤖 AI Response",
                lines=6
            )

    gr.Markdown("## 🔍 AI Investigation")

    with gr.Row():

        customer_info = gr.Textbox(
            label="👤 Customer Context",
            lines=7
        )

        analysis_info = gr.Textbox(
            label="🧠 AI Analysis",
            lines=7
        )

    with gr.Row():

        action_info = gr.Textbox(
            label="⚙️ Autonomous Action",
            lines=7
        )

        knowledge_info = gr.Textbox(
            label="📚 Knowledge Reasoning",
            lines=7
        )

    gr.Markdown("## 🤝 Human Agent Handoff")

    handoff_info = gr.Code(
        label="Complete Escalation Context",
        language="json"
    )

    analyze_button.click(
        fn=run_support,
        inputs=[customer_id, message],
        outputs=[
            response,
            customer_info,
            analysis_info,
            action_info,
            knowledge_info,
            handoff_info
        ]
    )


print("✅ Gradio dashboard created successfully.")

demo.launch()
